const express = require('express');
//const functions = require('firebase-functions');
const { NlpManager } = require('node-nlp');

// create a new instance of the NLP manager
const manager = new NlpManager({ languages: ['en'] });

// add training data for intents and entities 
manager.addDocument('en', 'hello', 'greetings');
manager.addDocument('en', 'hi there', 'greetings');
manager.addDocument('en', 'what is your name', 'get_name');
manager.addDocument('en', 'what time is it', 'get_time');
manager.addDocument('en', 'I want to buy shib', 'buy_shib');
manager.addDocument('en', 'Can I purchase shib?', 'buy_shib');
manager.addDocument('en', 'Where can I buy shib?', 'buy_shib');
manager.addDocument('en', 'I would like to buy some shib', 'buy_shib');
manager.addDocument('en', 'I want to purchase shib coins', 'buy_shib');
manager.addDocument('en', 'Can I buy shib with USD?', 'buy_shib');
manager.addDocument('en', 'How do I buy shib?', 'buy_shib');
manager.addDocument('en', 'What\'s the best way to buy shib?', 'buy_shib');
manager.addDocument('en', 'I need to buy shib', 'buy_shib');
manager.addDocument('en', 'I\'m interested in buying shib', 'buy_shib');
manager.addDocument('en', 'Where can I purchase shib?', 'buy_shib');
manager.addDocument('en', 'How can I buy shib?', 'buy_shib');
manager.addDocument('en', 'What is the process to buy shib?', 'buy_shib');
manager.addDocument('en', 'What\'s the price to buy shib?', 'get_shib_price');
manager.addDocument('en', 'What\'s the current price of shib?', 'get_shib_price');
manager.addDocument('en', 'How much does shib cost?', 'get_shib_price');
manager.addDocument('en', 'What\'s the cost to buy shib?', 'get_shib_price');
manager.addDocument('en', 'What is the price of shib coin?', 'get_shib_price');
manager.addDocument('en', 'Can you tell me the shib coin price?', 'get_shib_price');
manager.addDocument('en', 'What\'s the value of shib?', 'get_shib_price');
manager.addDocument('en', 'What\'s the shib coin rate today?', 'get_shib_price');
manager.addDocument('en', 'What\'s the price chart of shib?', 'get_shib_price');
manager.addDocument('en', 'Is there any discount on shib?', 'get_shib_discount');
manager.addDocument('en', 'Can I get a discount on buying shib?', 'get_shib_discount');
manager.addDocument('en', 'Are there any deals on shib?', 'get_shib_discount');
manager.addDocument('en', 'What\'s the discount for shib?', 'get_shib_discount');
manager.addDocument('en', 'Can I get a promo code for shib?', 'get_shib_discount');
manager.addDocument('en', 'Is there a sale on shib?', 'get_shib_discount');
manager.addDocument('en', 'I want to buy ethereum', 'buy_ethereum');
manager.addDocument('en', 'Can I purchase ethereum?', 'buy_ethereum');
manager.addDocument('en', 'Where can I buy ethereum?', 'buy_ethereum');
manager.addDocument('en', 'I would like to buy some ethereum', 'buy_ethereum');
manager.addDocument('en', 'I want to purchase ethereum coins', 'buy_ethereum');
manager.addDocument('en', 'Can I buy eth with USD?', 'buy_ethereum');
manager.addDocument('en', 'How do I buy eth?', 'buy_ethereum');
manager.addDocument('en', 'What\'s the best way to buy ethereum?', 'buy_ethereum');
manager.addDocument('en', 'I need to buy ethereum', 'buy_ethereum');
manager.addDocument('en', 'I\'m interested in buying ethereum', 'buy_ethereum');
manager.addDocument('en', 'Where can I purchase ethereum?', 'buy_ethereum');
manager.addDocument('en', 'How can I buy ethereum?', 'buy_ethereum');
manager.addDocument('en', 'What is the process to buy ethereum?', 'buy_ethereum');
manager.addDocument('en', 'What\'s the price to buy ethereum?', 'get_ethereum_price');
manager.addDocument('en', 'What\'s the current price of ethereum?', 'get_ethereum_price');
manager.addDocument('en', 'How much does ethereum cost?', 'get_ethereum_price');
manager.addDocument('en', 'What\'s the cost to buy ethereum?', 'get_ethereum_price');
manager.addDocument('en', 'What is the price of ethereum coin?', 'get_ethereum_price');
manager.addDocument('en', 'Can you tell me the ethereum coin price?', 'get_ethereum_price');
manager.addDocument('en', 'What\'s the value of ethereum?', 'get_ethereum_price');
manager.addDocument('en', 'What\'s the ethereum coin rate today?', 'get_ethereum_price');
manager.addDocument('en', 'What\'s the price chart of ethereum?', 'get_ethereum_price');
manager.addDocument('en', 'Is there any discount on eth?', 'get_ethereum_discount');
manager.addDocument('en', 'Can I get a discount on buying ethereum?', 'get_ethereum_discount');
manager.addDocument('en', 'Are there any deals on ethereum?', 'get_ethereum_discount');
manager.addDocument('en', 'What\'s the discount for eth?', 'get_ethereum_discount');
manager.addDocument('en', 'Can I get a promo code for ethereum?', 'get_ethereum_discount');
manager.addDocument('en', 'Is there a sale on ethereum?', 'get_ethereum_discount');
manager.addDocument('en', 'I want to buy bitcoin', 'buy_bitcoin');
manager.addDocument('en', 'Can I purchase bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'Where can I buy bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'I would like to buy some bitcoin', 'buy_bitcoin');
manager.addDocument('en', 'I want to purchase bitcoin coins', 'buy_bitcoin');
manager.addDocument('en', 'Can I buy btc with USD?', 'buy_bitcoin');
manager.addDocument('en', 'How do I buy btc?', 'buy_bitcoin');
manager.addDocument('en', 'What\'s the best way to buy bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'I need to buy bitcoin', 'buy_bitcoin');
manager.addDocument('en', 'I\'m interested in buying bitcoin', 'buy_bitcoin');
manager.addDocument('en', 'Where can I purchase bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'How can I buy bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'What is the process to buy bitcoin?', 'buy_bitcoin');
manager.addDocument('en', 'What\'s the price to buy bitcoin?', 'get_bitcoin_price');
manager.addDocument('en', 'What\'s the current price of bitcoin?', 'get_bitcoin_price');
manager.addDocument('en', 'How much does bitcoin cost?', 'get_bitcoin_price');
manager.addDocument('en', 'What\'s the cost to buy bitcoin?', 'get_bitcoin_price');
manager.addDocument('en', 'What is the price of bitcoin coin?', 'get_bitcoin_price');
manager.addDocument('en', 'Can you tell me the bitcoin coin price?', 'get_bitcoin_price');
manager.addDocument('en', 'What\'s the value of bitcoin?', 'get_bitcoin_price');
manager.addDocument('en', 'What\'s the bitcoin coin rate today?', 'get_bitcoin_price');
manager.addDocument('en', 'What\'s the price chart of bitcoin?', 'get_bitcoin_price');
manager.addDocument('en', 'Is there any discount on btc?', 'get_bitcoin_discount');
manager.addDocument('en', 'Can I get a discount on buying bitcoin?', 'get_bitcoin_discount');
manager.addDocument('en', 'Are there any deals on bitcoin?', 'get_bitcoin_discount');
manager.addDocument('en', 'What\'s the discount for btc?', 'get_bitcoin_discount');
manager.addDocument('en', 'Can I get a promo code for bitcoin?', 'get_bitcoin_discount');
manager.addDocument('en', 'Is there a sale on bitcoin?', 'get_bitcoin_discount');
manager.addDocument('en', 'I want to buy Dogecoin', 'buy_Dogecoin');
manager.addDocument('en', 'Can I purchase Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'Where can I buy Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'I would like to buy some Dogecoin', 'buy_Dogecoin');
manager.addDocument('en', 'I want to purchase Dogecoin coins', 'buy_Dogecoin');
manager.addDocument('en', 'Can I buy doge with USD?', 'buy_Dogecoin');
manager.addDocument('en', 'How do I buy doge?', 'buy_Dogecoin');
manager.addDocument('en', 'What\'s the best way to buy Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'I need to buy Dogecoin', 'buy_Dogecoin');
manager.addDocument('en', 'I\'m interested in buying Dogecoin', 'buy_Dogecoin');
manager.addDocument('en', 'Where can I purchase Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'How can I buy Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'What is the process to buy Dogecoin?', 'buy_Dogecoin');
manager.addDocument('en', 'What\'s the price to buy Dogecoin?', 'get_Dogecoin_price');
manager.addDocument('en', 'What\'s the current price of Dogecoin?', 'get_Dogecoin_price');
manager.addDocument('en', 'How much does Dogecoin cost?', 'get_Dogecoin_price');
manager.addDocument('en', 'What\'s the cost to buy Dogecoin?', 'get_Dogecoin_price');
manager.addDocument('en', 'What is the price of Dogecoin coin?', 'get_Dogecoin_price');
manager.addDocument('en', 'Can you tell me the Dogecoin coin price?', 'get_Dogecoin_price');
manager.addDocument('en', 'What\'s the value of Dogecoin?', 'get_Dogecoin_price');
manager.addDocument('en', 'What\'s the Dogecoin coin rate today?', 'get_Dogecoin_price');
manager.addDocument('en', 'What\'s the price chart of Dogecoin?', 'get_Dogecoin_price');
manager.addDocument('en', 'Is there any discount on doge?', 'get_Dogecoin_discount');
manager.addDocument('en', 'Can I get a discount on buying Dogecoin?', 'get_Dogecoin_discount');
manager.addDocument('en', 'Are there any deals on Dogecoin?', 'get_Dogecoin_discount');
manager.addDocument('en', 'What\'s the discount for doge?', 'get_Dogecoin_discount');
manager.addDocument('en', 'Can I get a promo code for Dogecoin?', 'get_Dogecoin_discount');
manager.addDocument('en', 'Is there a sale on Dogecoin?', 'get_Dogecoin_discount');
manager.addDocument('en', 'I need some help', 'request_assistance');
manager.addDocument('en', 'I need help', 'request_assistance');
manager.addDocument('en', 'Can you assist me?', 'request_assistance');
manager.addDocument('en', 'I require assistance', 'request_assistance');
manager.addDocument('en', 'I\'m having an issue', 'request_assistance');
manager.addDocument('en', 'I need your help', 'request_assistance');
manager.addDocument('en', 'Please help me', 'request_assistance');
manager.addDocument('en', 'Can you help me with this?', 'request_assistance');
manager.addDocument('en', 'I\'m not sure what to do', 'request_assistance');
manager.addDocument('en', 'I\'m stuck and need help', 'request_assistance');
manager.addDocument('en', 'I need some guidance', 'request_assistance');
manager.addDocument('en', 'help me please', 'request_assistance');
manager.addDocument('en', 'Can you please assist me?', 'request_assistance');
manager.addDocument('en', 'I need some support', 'request_assistance');
manager.addDocument('en', 'I\'m experiencing an issue', 'request_assistance');
manager.addDocument('en', 'I\'m having trouble with something', 'request_assistance');
manager.addDocument('en', 'I\'m lost and need help', 'request_assistance');
manager.addDocument('en', 'i am looking for help', 'request_assistance');
manager.addDocument('en', 'Can someone help me please?', 'request_assistance');
manager.addDocument('en', 'I need some advice', 'request_assistance');
manager.addDocument('en', 'I require some help and guidance', 'request_assistance');
manager.addDocument('en', 'Can you help me figure this out?', 'request_assistance');
manager.addDocument('en', 'I\'m struggling with this', 'request_assistance');
manager.addDocument('en', 'I need assistance with this matter', 'request_assistance');
manager.addDocument('en', 'Can you help me solve this problem?', 'request_assistance');
manager.addDocument('en', 'I\'m not able to do this myself', 'request_assistance');
manager.addDocument('en', 'I\'m not sure how to proceed', 'request_assistance');
manager.addDocument('en', 'Can you help me navigate this?', 'request_assistance');
manager.addDocument('en', 'I\'m having difficulties with this task', 'request_assistance');
manager.addDocument('en', 'I need your support', 'request_assistance');
manager.addDocument('en', 'Can you provide me with some assistance?', 'request_assistance');
manager.addDocument('en', 'I\'m stuck and don\'t know what to do', 'request_assistance');
manager.addDocument('en', 'I\'m having an emergency, can you help me?', 'request_assistance');
manager.addDocument('en', 'Just looking around', 'browsing');
manager.addDocument('en', 'I\'m not sure what I want', 'browsing');
manager.addDocument('en', 'I\'m just browsing', 'browsing');
manager.addDocument('en', 'I\'m not ready to buy yet', 'browsing');
manager.addDocument('en', 'I\'m exploring my options', 'browsing');
manager.addDocument('en', 'I\'m not in a hurry to purchase', 'browsing');
manager.addDocument('en', 'I\'m not committed to buying', 'browsing');
manager.addDocument('en', 'I\'m just window shopping', 'browsing');
manager.addDocument('en', 'I\'m not sure if I want to buy', 'browsing');
manager.addDocument('en', 'I\'m just checking things out', 'browsing');
manager.addDocument('en', 'I\'m not looking to buy anything right now', 'browsing');
manager.addDocument('en', 'I\'m not looking for anything specific', 'browsing');
manager.addDocument('en', 'I\'m not in the market to buy', 'browsing');
manager.addDocument('en', 'I\'m not interested in purchasing', 'browsing');
manager.addDocument('en', 'I\'m just browsing for now', 'browsing');
manager.addDocument('en', 'I\'m not committed to a purchase yet', 'browsing');
manager.addDocument('en', 'i looking for something', 'browsing');
manager.addDocument('en', 'I\'m not planning on buying anything', 'browsing');
manager.addDocument('en', 'I\'m just looking at what\'s available', 'browsing');
manager.addDocument('en', 'I\'m not sure if I\'m ready to buy', 'browsing');
manager.addDocument('en', 'I\'m not looking to make a purchase at the moment', 'browsing');
manager.addDocument('en', 'I\'m just exploring my options for now', 'browsing');
manager.addDocument('en', 'I\'m not sure if I want to make a purchase yet', 'browsing');
manager.addDocument('en', 'I\'m not actively shopping', 'browsing');
manager.addDocument('en', 'I\'m just checking out what\'s out there', 'browsing');
manager.addDocument('en', 'I\'m not certain if I want to buy', 'browsing');
manager.addDocument('en', 'I\'m not interested in buying anything at this time', 'browsing');
manager.addDocument('en', 'I\'m not committed to buying anything right now', 'browsing');
manager.addDocument('en', 'I\'m not looking to make a decision yet', 'browsing');
manager.addDocument('en', 'I\'m just browsing without any specific goal', 'browsing');
manager.addDocument('en', 'I want to create a new account', 'create_account');
manager.addDocument('en', 'How do I create a new account?', 'create_account');
manager.addDocument('en', 'Can I create a new account?', 'create_account');
manager.addDocument('en', 'What do I need to create a new account?', 'create_account');
manager.addDocument('en', 'Is it possible to create a new account?', 'create_account');
manager.addDocument('en', 'I need to create a new account', 'create_account');
manager.addDocument('en', 'I would like to create a new account', 'create_account');
manager.addDocument('en', 'Please help me create a new account', 'create_account');
manager.addDocument('en', 'I am interested in creating a new account', 'create_account');
manager.addDocument('en', 'How can I sign up for a new account?', 'create_account');
manager.addDocument('en', 'What is the process for creating a new account?', 'create_account');
manager.addDocument('en', 'I want to register for a new account', 'create_account');
manager.addDocument('en', 'I need assistance creating a new account', 'create_account');
manager.addDocument('en', 'How do I go about creating a new account?', 'create_account');
manager.addDocument('en', 'I\'m having trouble creating a new account', 'create_account');
manager.addDocument('en', 'I want to open a new account', 'create_account');
manager.addDocument('en', 'I\'m interested in setting up a new account', 'create_account');
manager.addDocument('en', 'What are the steps for creating a new account?', 'create_account');
manager.addDocument('en', 'How do I get started with creating a new account?', 'create_account');
manager.addDocument('en', 'I don\'t have an account and I want to create one', 'create_account');
manager.addDocument('en', 'I\'m a new user and I want to create an account', 'create_account');
manager.addDocument('en', 'I want to make a new account', 'create_account');
manager.addDocument('en', 'How can I create a new account?', 'create_account');
manager.addDocument('en', 'I\'m interested in creating an account, can you help?', 'create_account');
manager.addDocument('en', 'I need to set up a new account, what do I do?', 'create_account');
manager.addDocument('en', 'What information do I need to create a new account?', 'create_account');
manager.addDocument('en', 'I want to become a member, how do I create an account?', 'create_account');
manager.addDocument('en', 'Can you walk me through the process of creating a new account?', 'create_account');
manager.addDocument('en', 'I\'m ready to create a new account, what do I do?', 'create_account');
manager.addDocument('en', 'How do I go about setting up a new account?', 'create_account');
manager.addDocument('en', 'I want to start an account with you, how do I create one?', 'create_account');
manager.addDocument('en', 'I am new here', 'create_account');

// train the NLP manager
(async () => {
  await manager.train();
  manager.save();
})();

// create a new express app
const app = express();

// create an API endpoint for detecting the intent of a given text input
app.get('/detect_intent', async (req, res) => {
  const { text } = req.query;
  const response = await manager.process('en', text);
  res.send(response.intent);
});

// start the express app
app.listen(3000, () => console.log('Server started on port 3000'));
//exports.api=functions.https.onRequest(app)
